<div class="team_desc">
    <h1>MVSR Engineering College</h1> Maturi Venkata Subba Rao Engineering College, was established in 1981. It is one of the earliest of the colleges in the state of Andhra Pradesh, India, that pioneered engineering education in private sector. The college was founded by Matrusri Education Society, whose members distinguished themselves as engineers, doctors, accountants, lawyers, businessmen and administrators. After completing two decades of excellent service in Technical Education, the college has celebrated its Silver Jubilee year in February 2007.

    <h2>Our Vision</h2>
    To Impart technical education of the highest standards, producing technically competent confident and socially responsible engineers

    <h2>Our Mission</h2>
    To Impart adequate fundamental knowledge,technical and soft skils to students.
    To make learning process exciting,stimulating and joyful.
    To create a climate conducive to excellent teaching - learning Process.
    To bring out creativity in students.
    To contribute to advancement of engineering & technology.
    To make positive contribution to meet societal needs.
</div>







