<div class="team_desc">
    <h1>Khoj - Online Tresure Hunt</h1> 
    <p>Have  you always wanted to have treasure hunt like Indiana Jones and Pirates of Caribbean. Do you always read Detective Novels. Do you see finer details about the things around that everyone fails to see. Then we Khoj Team give you challenge that you will never forget. A Challenege that will you will have to give more and more of your wits to solve the complicated problems.</p>
</div>








