<div class="team_desc">
    <h1>Sangamam</h1> 
    It is a National Level Cultral Fest conducted by MVSR Engineering College. Students all over from india come and attend the fest. There will be a Desi Day with traditional events such as Desi Walk, Traditional Dressing, Mehendi etc.. Followed by two days of cultural events as Singing, Dancing. The Last Day of Sangamam is enjoyed with a Disco Night. Famous Celebrities have been at Sangamam to mesmerize the crowd.
    
    <h2>Samavarthan</h2>
    It is a National Level Technical Fest conducted by MVSR Engineering College. It spans for three days, that includes numerous events. Online Events Treasure Hunt, Online COding Competition and Oncampus Events for every branch. Prizes of worth 2,00,00 Rupees are distributed every year. The Fest gets participation from number of colleges.
</div>
