<div class="team_desc">This is a CMS for the popular Tresure Hunt that is conducted as a part of Technical Fest across India. Now for every College that conducts Treasure Hunt as an event don't have to develop their own code for the event site. You can use the CMS to change the questions and upload the site
    Features:
    <ul>
        <li>Powered by Zend Framework, PHP, MySQL</li>
        <li>Flexible Options in the admin Panel</li>
        <li>Facebook Integration (Login and Registration)</li>
        <li>Separate User Profiles</li>
        <li>Discussion Forum every Question</li>
        <li>Site Tour – to present yourselves to the first visitors of the site</li>
        <li>Gamification through New Metrics for User Progress bypoints</li>
        <li>We will be launching the CMS on Feb 15, 2013</li>
        <li>We offer free support for implementation of the platform</li>
        <li>We are Open Source and available on GitHub <a href="github.com/jrahulroy/khoj-cms">http://github.com/jrahulroy/khoj-cms</a></li>
    </ul>
</div>





