<div id="footer">
		<div id="footerwrap">
			<div class="footerminibox">
				<div class="footertitle">Resources</div>
				<div class="footerposts">
				<ul>
					<li><a href="http://www.google.com/">Google</a></li>
					<li><a href="http://www.bing.com/">Bing</a></li>
					<li><a href="http://www.wikipedia.com/">Wikipedia</a></li>
				</ul>
				</div>
			</div>
			<div class="footerminibox">
				<div class="footertitle">About Us</div>
				<div class="footerposts">
				<ul>
					<li><a href="<?php echo $this->baseUrl('aboutus/event')?>">The Event</a></li>
					<li><a href="<?php echo $this->baseUrl('aboutus/fest')?>">The Fest</a></li>
					<li><a href="<?php echo $this->baseUrl('aboutus/college')?>">The College</a></li>
					<li><a href="<?php echo $this->baseUrl('aboutus/team')?>">The Khoj Team</a></li>
					<!--<li><a href="<?php echo $this->baseUrl('aboutus/khoj')?>">The Khoj CMS</a></li>
					<li><a href="<?php echo $this->baseUrl('aboutus/tinycreations')?>">The Tiny Creations</a></li>-->
				</ul>
				</div>
			</div>
			<div class="footerminibox">
				<div class="footertitle">Social</div>
				<div class="footersocial">
				<ul>
					<li><a href="https://www.facebook.com/KhojTheHunt.tk"><img src="<?php echo $this->baseUrl('images/icons/facebook_16.png'); ?>" alt="facebook" /> Facebook</a></li>
					<!--<li><a href="#"><img src="<?php echo $this->baseUrl('images/icons/twitter_16.png'); ?>" alt="twitter" /> Twitter</a></li>-->
					

				</ul>
				</div>
			</div>
			<div class="footerbox footerspace">
				<div class="footertitle">About us</div>
				<div class="footertext">
					<!--<div class="aboutimage">
						<a href="#"><img src="images/footer/about.jpg" alt="photo" /></a>
					</div>-->
				The Platform is Powered by Khoj CMS. For more details  <a href="http://github.com/jrahulroy/khoj-cms">Check out GitHub</a>
				</div>
			</div>
			<div class="footerbox footerspace">
                            <!-- Also We can give informative System Details or a powered by logo-->
				<div class="footertitle">Sponsors</div>
					<div class="footeraddress">
						<ul>
							<li>------------------</li>
							<li>------------------</li>
							<li>------------------</li>		
						</ul>
					</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
	<div id="footerbarwrap">
	<ul>
	<script type="text/javascript">
</script>
		<li>
<li>Copyright &copy; Tiny Creations. All rights reserved.</li>
	</ul>
	</div>
</div>