<?php $khojconfig = Zend_Registry::get('khoj-config'); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <title><?php echo $khojconfig->layout->websiteTitle; ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <link rel="Shortcut Icon" type="image/ico" href="<?php echo $this->baseUrl('favicon.ico'); ?>" />
        <link href="<?php echo $this->baseUrl('css/style.css'); ?>" rel="stylesheet" type="text/css" />
        <!--<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/jquery.jcarousel.css'); ?>" />-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/colorbox.css'); ?>" />
        <!--<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/jcarousel.skin.css'); ?>" />-->
        <link href="<?php echo $this->baseUrl('css/ddsmoothmenu.css'); ?>" rel="stylesheet" type="text/css" />

        <!--[if lte IE 6]>
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/ie6.css'); ?>" media="screen" />
        <![endif]-->

        <!--[if IE 7]>
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/ie7.css'); ?>" media="screen" />
        <![endif]-->


        <!-- JQUERY Library -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.3.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/colorbox/jquery.colorbox-min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jcarousel/jquery.jcarousel.pack.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/fadeinout.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/cufon-yui.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/Museo_Sans_500.font.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/fontconfig.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/menu/ddsmoothmenu.js'); ?>">
            /***********************************************
             * Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
             * This notice MUST stay intact for legal use
             * Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
             ***********************************************/
        </script>
        <!-- Initiate carousel with 4 image blocks -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/common.js'); ?>"></script>
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo $khojconfig->facebook->appId; ?>";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        <div id="pagecontainer"> <!-- Outside Container -->
            <div id="mainpage"> 
                    <?php echo $this->render('header.phtml') ?>
                    <div id="categorytitle">
                    <?php echo $this->title ?>
                    <?php echo $this->profileLink() ?>
                </div>
                <div id="contents" >
                    <?php echo $this->layout()->content; ?>
                </div>
                <div class="clear"></div>
            </div> <!-- Close Mainpage -->
            <!-- Footer start -->
            <?php echo $this->render('footer.phtml') ?>
            <script type="text/javascript"> Cufon.now();</script>
    </body>
</html>