<?php $khojconfig = Zend_Registry::get('khoj-config'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <title>Khoj - Welcome</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <meta name="description" content="Khoj- The Online Tresure Hunt" />
        <meta name="keywords" content="online, treasure, hunt, game, fest, college"/>
        <link rel="Khoj Icon" type="image/ico" href="favicon.ico" />
        <link href="<?php echo $this->baseUrl('css/style.css'); ?>" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/colorbox.css'); ?>" />
        <link href="<?php echo $this->baseUrl('css/ddsmoothmenu.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl('css/kwicks.css'); ?>" rel="stylesheet" type="text/css" />
        <!--[if lte IE 6]>
        <link rel="stylesheet" type="text/css" href="css/ie6.css" media="screen" />
        <![endif]--><!--[if IE 7]>
        <link rel="stylesheet" type="text/css" href="css/ie7.css" media="screen" />
        <![endif]-->
        <!-- JQUERY Library -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.3.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/colorbox/jquery.colorbox-min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jcarousel/jquery.jcarousel.pack.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/fadeinout.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/cufon-yui.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/Museo_Sans_500.font.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/fontconfig.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/menu/ddsmoothmenu.js'); ?>"></script>
        <!-- Kwicks Accordion and Easing -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/kwicks/jquery.easing.1.3.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/kwicks/jquery.kwicks-1.5.1.pack.js'); ?>"></script>
        <!-- Kwicks Custom and Initializing -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/kwicks/kwicks-custom.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/common.js'); ?>"></script>
    </head>
    <body>
        <div id="mainpagecontainer">
            <!-- Outside Container -->
            <div id="mainpage">
                <div id="mainpageheader">
                    <!-- Header Start -->
                    <?php echo $this->render('pheader.phtml'); ?>
                </div>
                <!-- Close Header -->
                <!-- Featured Block -->
                <div class="container">
                    <ul class="kwicks horizontal" >
                        <!-- Item One -->
                        <li id="kwickblock1">
                            <div>
                                <!-- Dropshadow PNG through CSS -->
                                <div class="kwickshadow"> </div>
                                <!-- Featured Image one -->
                                <a href="#"><img class="slideimage" src="<?php echo $this->baseUrl('images/accordion/image1.jpg'); ?>" alt="First Image" /></a>
                                <!-- Mini Caption when slide closed -->
                                <p class="slide-minicaption">
                                    <span class="slide-minicaptiontitle">
                                        Khoj The Online Tresure Hunt
                                    </span>
                                </p>
                                <!-- Big Caption on Hover -->
                                <p class="slidecaption">
                                    <span class="slidecaptiontitle">
                                        <a href="#">Khoj The Online Tresure Hunt</a>
                                    </span>
                                    <a href="#">MVSR Engineering College presents Online Tresure Hunt as a part of Sagamam 2013, Annual Cultural Fest.</a>
                                </p>
                            </div>
                        </li>
                        <!-- Item End -->
                        <!-- Item Start - Refer to first item for explanation -->
                        <li id="kwickblock2">
                            <div>
                                <div class="kwickshadow">
                                </div>
                                <a href="#"><img class="slideimage" src="<?php echo $this->baseUrl('images/accordion/image2.jpg'); ?>" alt="Second Image" /></a>
                                <p class="slide-minicaption">
                                    <span class="slide-minicaptiontitle">
                                        Sangamam 2013
                                    </span>
                                </p>
                                <p class="slidecaption">
                                    <span class="slidecaptiontitle">
                                        <a href="#">Sangamam 2013</a>
                                    </span>
                                    <a href="#">Sangamam is back this time with more Dhamaka. Come and Enjoy on February 21, 22 and 23.</a>
                                </p>
                            </div>
                        </li>
                        <!-- Item End -->				
                        <!-- Item Start - Refer to first item for explanation -->
                        <li id="kwickblock3">
                            <div>
                                <div class="kwickshadow"> </div>
                                <a href="#"><img class="slideimage" src="<?php echo $this->baseUrl('images/accordion/image3.jpg'); ?>" alt="Third Image" /></a>
                                <p class="slide-minicaption">
                                    <span class="slide-minicaptiontitle">
                                        Pro Night
                                    </span>
                                </p>
                                <p class="slidecaption">
                                    <span class="slidecaptiontitle">
                                        <a href="#">Pro Night</a>
                                    </span>
                                    <a href="#">This time we have Suraj Jagan of "Give Me Some Sunshine" Fame, to sing and make dance.</a>						
                                </p>
                            </div>
                        </li>
                        <!-- Item End -->				
                        <!-- Item Start - Refer to first item for explanation -->
                        <li id="kwickblock4">
                            <div>
                                <a href="#"><img class="slideimage" src="<?php
                                    echo $this->baseUrl('images/accordion/image4.jpg');
                                    ?>" alt="Fourth Image" /></a>
                                <p class="slide-minicaption">
                                    <span class="slide-minicaptiontitle">
                                        Ultimate Survivor
                                    </span>
                                </p>
                                <p class="slidecaption">
                                    <span class="slidecaptiontitle">
                                        <a href="#">Ultimate Survivor</a>
                                    </span>
                                    <a href="#">The Biggest Event of the Sangamam. The event tests the team participants in all aspects.
                                        The Winning Team gets an "IPHONE 5". Hurry Up and Register Now. Limited Registrations.</a>
                                </p>
                            </div>
                        </li>
                        <!-- Item End -->
                    </ul>
                </div>
                <div class="clear"></div>
                <!-- End of Featured Block -->
                <div class="clear"></div>
                <!-- Clear Floats -->		<!-- Big Saying with Button -->
                <div class="mbigsaying">
                    <div class="mbigbutton">
                        <span><a href="/hunt/dashboard">PlayNow</a></span>
                    </div>
                    <div class="mbigtextwrap">
                        <div class="mbigtitle">
                            Khoj - The Online Treasure Hunt
                        </div>
                        <div class="mbigdesc"><br />
                            Have you always wanted to have treasure hunt like Indiana Jones and Pirates of Caribbean.
                            Do you always read Detective Novels. Do you see finer details about the things around that everyone
                            fails to see.<br /><br />
                        </div>
                        <div class="mbigdesc">
                            Then we Khoj Team give you challenge that you will never forget.
                            A Challenege that you will have to give more and more of your wits to solve the complicated problems.
                            <br />
                            <br />
                        </div>
                        <div class="mbigdesc">
                            Welcome to Khoj 2013, An Online Treasure Hunt Challenge conducted as a part of All India Cultural
                            Fest, Sangamam 2013 by MVSR Engineering College.<br />
                        </div>
                    </div>
                    <br /><br /><br />
                    <div class="mbigtextwrap">
                        <br /><br />
                        <div class="mbigtitle">
                            How To Play
                        </div>
                        <div class="mbigdesc"><br />
                            This Event consists of series of images, that give certain clue for a keyword or a series of keywords.
                            People can use their intelligence, cunningness, and with search engine help, the participant have to break
                            the clues and find the keyword, only go to next question. The answer to a question may include a keyword or
                            a group of keywrods, and order may be sometime important.
                        </div>
                    </div>
                    <br />
                    <div class="mbigtextwrap">
                        <br />
                        <div class="mbigtitle">
                            Rules
                        </div>
                        <div class="mbigdesc"><br />
                            1. All the characters in the answer are small letters<br />
                            2. There are no Spaces in the answer<br />
                            3. There are no special characters<br />
                            4. Be decent on Facebook Page. Misbehaviour or revealing answers can lead to ban<br />
                            5. Look for hints in our Facebook Page<br />
                        </div>
                    </div>
                </div>
                <!-- Big Saying Ends -->
                <div class="clear"></div>
                <!-- Three Steps with Icons and text -->
                <div id="mstepswrap">
                    <div class="mbigsaying">
                        <div class="mbigmorewrap">
                            <div class="mbigtitle">
                                <a target="_blank" href="http://mvsrsangamam.org">About Sangamam</a>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <!-- Step One -->
                    <div class="stepblock">
                        <!-- Icon -->
                        <div class="stepbullet">
                            <img src="images/buttons/1.png" alt="step one" />
                        </div>
                        <!-- Title and Text -->
                        <div class="stepcontents">
                            <div class="steptitle">
                                <a href="#">Desi Day <br /> Feb 21</a>
                            </div>
                            <div class="steptext">
                                Rangoli, Hop Scotch, Matke Ka Phatka, Desi Walk
                            </div>
                        </div>
                    </div>
                    <!-- Step One ends -->
                    <!-- Step Two -->
                    <div class="stepblock stepspace">
                        <div class="stepbullet">
                            <img src="images/buttons/2.png" alt="step two" />
                        </div>
                        <div class="stepcontents">
                            <div class="steptitle">
                                <a href="#">Cultural Events <br /> Feb 22</a>
                            </div>
                            <div class="steptext">
                                Quidditch, Telugu Extempore, Artemesis Quest, Bluff Master, Lan Gaming, Ultimate Survivor
                            </div>
                        </div>
                    </div>
                    <!-- Step Three -->
                    <div class="stepblock stepspace">
                        <div class="stepbullet">
                            <img src="images/buttons/3.png" alt="step three" />
                        </div>
                        <div class="stepcontents">
                            <div class="steptitle">
                                <a href="#">Musical Night <br />Feb 23</a>
                            </div>
                            <div class="steptext">
                                Ardour, La Triviata, Dice Race, Prolixo, Snap Star, Khoj The Hunt, Picture This, Funtastic, Stage Performence By Suraj Jagan
                            </div>
                        </div>
                    </div>
                    <div class="clear">
                    </div>
                </div>
                <!-- Three Steps End -->
                <div class="clear"></div>
                <!-- Portfolio Block -->
                <div id="mportfoliowrap">
                    <div class="mportfoliobox">
                        <!-- mportfoliobg will enable the background image which is seen on mouse over -->
                        <!-- Portfolio Block One-->
                        <div class="mportfolio mportfoliocatbg">
                            <a href="#">
                                <!-- Class fade will enable fade in out -->
                                <img class="fade columnimage1" src="images/portfolio3.png" alt="Portfolio" />
                            </a>
                        </div>
                    </div>
                    <div class="mportfoliobox mportfoliospace">
                        <div class="mportfolio mportfoliocatbg">
                            <!-- Portfolio Block Two -->
                            <a href="#">
                                <img class="fade columnimage2" src="images/portfolio1.png" alt="Portfolio" />
                            </a>
                        </div>
                    </div>
                    <div class="mportfoliobox mportfoliospace">
                        <div class="mportfolio mportfoliocatbg">
                            <!-- Portfolio Block Three -->
                            <a href="#">
                                <img class="fade columnimage3" src="images/portfolio2.png" alt="Portfolio" />
                            </a>
                        </div>
                    </div>
                    <div class="mportfoliobox mportfoliospace">
                        <div class="mportfolio mportfoliocatbg">
                            <!-- Portfolio Block Three -->
                            <a href="#">
                                <img class="fade columnimage4" src="images/portfolio4.png" alt="Portfolio" />
                            </a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                <!-- The can be 3 column of info on your company -->
                <div id="mblogwrap">
                    <div class="mblogbox">
                        <!-- Info Block One -->
                        <div class="mblogtitle columntitle1"><a href="#">LAN Gaming</a></div>
                        <div class="mblogtext">
                            FIFA, Counter-Strike, COD, Need for Speed, Age of Empires and DOTA, its all here. Counter-Strike is the oldest, and most popular -
                            consequently the bar for this game is set very high - the moment you blink, you are gone. Then here's FIFA'11 for football freaks.
                            Can't play it on the field? So what! Experience it virtually and feel the same pressure that players experience on the field.	
                        </div>
                    </div>
                    <div class="mblogbox mblogspace">
                        <!-- Info Block Two -->
                        <div class="mblogtitle columntitle2"><a href="#">Short Film Festival</a></div>
                        <div class="mblogtext">
                            Are you a Short film maker? Do you have that passion towards film making to overcome other film makers and stand apart from them?
                            Do you want to test your level of creativity in this ever competitive world??? Then this is the right chance for you!!!
                            <a target="_blank" href="https://docs.google.com/forms/d/1XTbhndzJKiWQAPGB0u5qX3mf_P4GosopV4ez7errbFI/viewform">Register Now</a>				
                        </div>
                    </div>
                    <div class="mblogbox mblogspace">
                        <!-- Info Block Three -->
                        <div class="mblogtitle columntitle3"><a href="#">Movie Making Workshop</a></div>
                        <div class="mblogtext">
                            A two-day 'MOVIE MAKING' workshop. The participants will get focussed on Script Writing, Camera Working, Film Editing
                            (Scene Decision, Visual Effects, Titling & Sound Effects).Workshop will be conducted on feb 17,18.
                            <a target="_blank" href="https://docs.google.com/forms/d/1ZEPHhbbDl2ITAnzfcC-lQV5UVe6EpAXf3xn6Q2MXP0g/viewform">Register Now</a>
                        </div>
                    </div>
                    <div class="mblogbox mblogspace">
                        <!-- Info Block Four -->
                        <div class="mblogtitle columntitle4"><a href="#">Ultimate Survivor</a></div>
                        <div class="mblogtext">
                            Ready to face challenges then the event is for you
                            <a target="_blank" href="https://docs.google.com/forms/d/1XsSCOmwo0K9Gpriuozm-4F7AiKpMPUxvMXPM98ykOCM/viewform">Register Now</a>				
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
                <!-- Another Big saying with Arrow -->
                <div class="mbigsaying">
                    <div class="mbigmorewrap">
                        <div class="mbigtitle">
                            <a target="_blank" href="http://mvsrsangamam.org">For Complete Details Check Sangamam Website</a>
                            <a target="_blank" href="http://mvsrsagamam.org" class="morearrow"></a>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <!-- Close Mainpage -->
            <!-- Footer start -->
            <?php echo $this->render('footer.phtml'); ?>
            <!-- Footer End -->
        </div>
        <!-- Close Container --><!-- Cufon Activation mainly for IE --><script type="text/javascript"> Cufon.now();</script>
    </body>