<?php $khojconfig = Zend_Registry::get('khoj-config'); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <title><?php echo $khojconfig->layout->websiteTitle; ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
        <meta property="fb:app_id" content="<?php echo $khojconfig->facebook->appId ?>"/>
        <meta property="fb:admins" content="1199891462,100000394783169"/>
        <link rel="Shortcut Icon" type="image/ico" href="<?php echo $this->baseUrl('favicon.ico'); ?>" />
        <link href="<?php echo $this->baseUrl('css/style.css'); ?>" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/jquery.jcarousel.css'); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/colorbox.css'); ?>" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/jcarousel.skin.css'); ?>" />
        <link href="<?php echo $this->baseUrl('css/ddsmoothmenu.css'); ?>" rel="stylesheet" type="text/css" />

        <!--[if lte IE 6]>
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/ie6.css'); ?>" media="screen" />
        <![endif]-->

        <!--[if IE 7]>
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/ie7.css'); ?>" media="screen" />
        <![endif]-->

        <!-- JQUERY Library -->
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.3.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/colorbox/jquery.colorbox-min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/jcarousel/jquery.jcarousel.pack.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/fadeinout.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/cufon-yui.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/Museo_Sans_500.font.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/fontconfig.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/menu/ddsmoothmenu.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/common.js'); ?>"></script>
        <script type="text/javascript">var switchTo5x = false;</script>
        <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
        <script type="text/javascript">stLight.options({publisher: "5c9df651-ae7f-4012-8122-055f96c60bf9", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo $khojconfig->facebook->appId; ?>";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        <div id="pagecontainer"> <!-- Outside Container -->
            <div id="mainpage"> 
                <?php echo $this->render('header.phtml') ?>
                <div id="categorytitle">
                    <?php echo $this->title ?>
                    <?php echo $this->profileLink() ?>
                </div>
                <div id="sidebar">
                    <?php
                    echo $this->render('timeline.phtml');

                    if ($this->renderLikebox) {
                        echo $this->render('likebox.phtml');
                    };
                    if ($this->renderPeopleSameLevel) {
                        echo $this->render('peoplesamelevel.phtml');
                    };
                    ?>
                    <div class="clear"></div>
                </div>
                <div id="contents" class="twocolumn">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div class="clear"></div>
            </div> <!-- Close Mainpage -->
            <!-- Footer start -->
            <?php echo $this->render('footer.phtml') ?>
            <script type="text/javascript"> Cufon.now();</script>
    </body>
</html>